### ISSUE TITLE
Association mode only triggers no-stimulus trials.

### ISSUE THREAD

**Issue by aprrenard** [LSENS-BMI-EPFL/behavior_control#30]
The association mode is meant to trigger the reward right after stimulus presentation to shape the association. It would be handy to fix/improve for convenience to avoid having to deliver reward manually during shaping. Switching to association during a session only presents blank stimuli. Also, late time I checked the GUI crashes when the association mode in on at trial 1.

**Comment by abisi** [comment]
Hm let me try to reproduce this
